[bin] Fix multiple bugs in malt script, mostly cmake temlate @ONLY missing and argument checking. (working on #14)

diff --git a/src/integration/malt.sh.in b/src/integration/malt.sh.in
--- a/src/integration/malt.sh.in
+++ b/src/integration/malt.sh.in
@@ -13,6 +13,15 @@ MPI_WRAPPER_DIR="$HOME/.malt"
 MALT_OPTIONS=""
 
 ######################################################
+maltCheckArgs()
+{
+	if [ -z "$2" ]; then
+		echo "MALT: Missing value for option '$1'" 1>&2
+		exit 1
+	fi
+}
+
+######################################################
 maltPrepMPI()
 {
 	#create dir
@@ -74,10 +83,12 @@ while true; do
 			exit 0
 		;;
 		--config|-c)
+			maltCheckArgs "$@"
 			export MALT_CONFIG="$2"
 			shift 2
 		;;
 		--stack|-s)
+			maltCheckArgs "$@"
 			export MALT_STACK="$2"
 			shift 2
 		;;
@@ -90,6 +101,7 @@ while true; do
 			shift 1
 		;;
 		--option|-o)
+			maltCheckArgs "$@"
 			export MALT_OPTIONS="${MALT_OPTIONS};$2"
 			shift 2
 		;;
@@ -99,7 +111,7 @@ while true; do
 			;;
 		--mpi)
 			ENABLE_MPI=true
-			if [ ! -e "$MPI_WRAPPER_DIR/libmaltmpi.so" ]; then
+			if [ ! -e "${MPI_WRAPPER_DIR}/libmaltmpi.so" ]; then
 				echo "Missing MPI wrapper to extract ranks, please prepare it with 'malt --prep-mpi=MPICXX' !"
 				exit 1
 			fi
@@ -133,14 +145,14 @@ done
 
 ######################################################
 MALT_LIB="@CMAKE_INSTALL_PREFIX@/lib@LIBSUFFIX@/libmalt.so"
-if [ ! -f $MALT_LIB ]; then
+if [ ! -f "${MALT_LIB}" ]; then
 	MALT_LIB="@CMAKE_INSTALL_PREFIX@/lib64/libmalt.so"
 fi
 
 ######################################################
 #run
-if [ "$ENABLE_MPI" = "true" ]; then
-	LD_PRELOAD="$MPI_WRAPPER_DIR/libmaltmpi.so $MALT_LIB" "$@"
+if [ "${ENABLE_MPI}" = "true" ]; then
+	LD_PRELOAD="${MPI_WRAPPER_DIR}/libmaltmpi.so:${MALT_LIB}:${LD_PRELOAD}" "$@"
 else
-	LD_PRELOAD="$MALT_LIB" "$@"
+	LD_PRELOAD="${MALT_LIB}:${LD_PRELOAD}" "$@"
 fi
